- hosts: web
  become: true
  tasks:
    - import_tasks: tasks/nginx.yml
  handlers:
    - import_tasks: handlers/nginx.yml

- hosts: web
  become: true
  tasks:
    - import_tasks: tasks/copy-website.yml
